### ISSUE TITLE
Ghorg ignoring private repos even with proper token permissions

### ISSUE THREAD

**Issue by dmriding** [gabrie30/ghorg#454]
When using this or a variation of this command:
ghorg clone [mygithubusername] --clone-type=user --token=[my token here] --path=/mnt/md0/ghorg 

ghorg is only able to find and clone repositories that are public, I tested my access token manually to ensure I did not miss some repo permissions when creating the token by using git clone and the access key is working with the proper permissions to clone the private repositories.

here is the partial output of my command:

 +-+-+-+-+ +-+-+ +-+-+-+-+-+
 |T|I|M|E| |T|O| |G|H|O|R|G|
 +-+-+-+-+ +-+-+ +-+-+-+-+-+

*************************************
* SCM           : github
* Type          : user
* Protocol      : https
* Location      : /mnt/md0/ghorg/
* Concurrency   : 25
* Config Used   : /home/username/.config/ghorg/conf.yaml
* Ghorg version : v1.9.13

then it tells me 29 repos found, however there should be 54 repos...

This is my private github user I'm trying to clone

OS I'm using is Ubuntu 24.04
I have tried classic tokens as well as fine grain tokens and both have the same issue. I have also tested both manually via git clone and this has no issues.

**Comment by gabrie30** [comment]
Thanks for raising this. It should be fixed on 1.9.14, if you have go installed you can clone the repo and go install it to get it now, otherwise I'll probably cut a release this weekend.

**Comment by gabrie30** [comment]
Just cut a new release @dmriding

**Comment by dmriding** [comment]
@gabrie30 amazing, I'll test it later today thank you!!

**Comment by dmriding** [comment]
@gabrie30 all is working now, thank you!

**Comment by League2EB** [comment]
@gabrie30 
@dmriding 
I'm sorry, I'm still encountering this issue.

*************************************
* SCM           : github
* Type          : user
* Protocol      : ssh
* Location      : /Users/league2eb/Documents/github/
* Concurrency   : 25
* Skip Forks    : true
* Wikis         : true
* Fetch All     : true
* Config Used   : /Users/league2eb/.config/ghorg/conf.yaml
* Ghorg version : v1.11.0
*************************************

In the conf.yaml, I did write down "personal access token", but when I ran "ghorg clone league2eb", the downloaded repositories only include public ones, not private repos.

I don't understand where I went wrong in the process. Please tell me. Thank you.
